name: fetch-new-commit-awesome-android
on:
  schedule:
    - cron:  '0 6 * * *'
    
#   workflow_run:
#     workflows: ["trigger-new-commit"]
#     types: [completed]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      SOURCE: 'JStumpp'
      REPO: 'awesome-android'
    steps:
      - uses: actions/checkout@v2
      - name: Checkout origin repo
        uses: Correia-jpv/action-sync-repo@main
        env:
          SECRET_TOKEN: ${{ secrets.PAT }}
        with:
          src_repo: ${{ env.SOURCE }}/${{ env.REPO }}
          src_branch: 'HEAD'
          dest_repo: correia-jpv/fucking-${{ env.REPO }}
          dest_branch: 'main'


      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2


      - name: Update README
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python fucking-awesome.py
        env:
          PAT: ${{ secrets.pat }}
          ORIGIN_REPO: https://raw.githubusercontent.com/correia-jpv/fucking-${{ env.REPO }}/main/readme.md


      - name: Pushes README
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source_file: 'results/readme.md'
          destination_repo: correia-jpv/fucking-${{ env.REPO }}
          user_email: 'correia-jpv@users.noreply.github.com'
          user_name: 'correia-jpv'
          commit_message: '⚡ Update README'
        
        